#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
step_sanitize.py — STEP (ISO 10303-21) ファイルから個人識別メタデータを除去する

消す・付け替えるもの
  HEADER : FILE_NAME の name(フルパスが入りがち) / timestamp / author /
           organization / preprocessor_version(CADソフト名) /
           originating_system / authorisation(承認者)
           FILE_DESCRIPTION の説明欄(ここにもソフト名が入りがち)
  DATA   : PERSON / ORGANIZATION / PERSONAL_ADDRESS / ORGANIZATIONAL_ADDRESS
           の文字列(氏名・メール・住所など。AP203系が書き込む)
           CALENDAR_DATE / LOCAL_TIME の日時 → 1970-01-01 00:00
           (--keep-dates で保持)
  共通   : /* コメント */ ("Generated by ..." 系。--keep-comments で保持)

触らないもの
  ジオメトリ・トポロジ等のエンティティは1バイトも変更しない

使い方
  python3 step_sanitize.py in.step --scan          # 何が入ってるか見るだけ
  python3 step_sanitize.py in.step                 # → in_clean.step
  python3 step_sanitize.py in.step -o out.step
  python3 step_sanitize.py in.step --name part.step --product part-A

依存パッケージなし。Python 3.8+ で動く。
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

# 文字列を全部空にするエンティティ(個人・組織情報)
SCRUB_STRING_ENTITIES = {
    "PERSON",
    "ORGANIZATION",
    "PERSONAL_ADDRESS",
    "ORGANIZATIONAL_ADDRESS",
}
# 日時を中和するエンティティ
DATE_ENTITIES = {"CALENDAR_DATE", "LOCAL_TIME"}

# STEP文字列: 'foo' 、内部の ' は '' でエスケープ
STRING_RE = re.compile(r"'(?:[^']|'')*'")
ENTITY_RE = re.compile(r"\s*#\d+\s*=\s*([A-Za-z0-9_]+)\s*\(")
HEADER_ENT_RE = re.compile(r"\s*([A-Za-z0-9_]+)\s*\(")
INT_RE = re.compile(r"^[+-]?\d+$")
REAL_RE = re.compile(r"^[+-]?(?:\d+\.\d*|\.\d+|\d+)(?:[Ee][+-]?\d+)?$")
# 非ASCII文字のSTEPエスケープ (\X2\=UTF-16BE, \X4\=UTF-32BE)。
# スキーマ語彙には絶対に現れない = 中身は必ずユーザー由来(フィーチャー名等)
X_ESC_RE = re.compile(r"\\X[24]\\")
X2_RE = re.compile(r"\\X2\\([0-9A-Fa-f]+)\\X0\\")
X4_RE = re.compile(r"\\X4\\([0-9A-Fa-f]+)\\X0\\")

EPOCH_TS = "1970-01-01T00:00:00"


# ---------------------------------------------------------------- 低レベル処理

def load(path: Path) -> str:
    # latin-1 はバイト⇔文字が1:1なので、任意のバイト列(UTF-8日本語含む)を
    # 完全にラウンドトリップできる
    with open(path, "r", encoding="latin-1", newline="") as f:
        return f.read()


def save(path: Path, text: str) -> None:
    with open(path, "w", encoding="latin-1", newline="") as f:
        f.write(text)


def to_raw(s: str) -> str:
    """コマンドライン引数(UTF-8のstr)を latin-1 透過表現に変換"""
    return s.encode("utf-8").decode("latin-1")


def _dec(m, enc):
    try:
        return bytes.fromhex(m.group(1)).decode(enc)
    except (ValueError, UnicodeDecodeError):
        return m.group(0)


def display(s: str) -> str:
    """レポート表示用: UTF-8デコード + \\X2\\/\\X4\\ エスケープの可読化"""
    try:
        s = s.encode("latin-1").decode("utf-8")
    except UnicodeError:
        pass
    s = X2_RE.sub(lambda m: _dec(m, "utf-16-be"), s)
    s = X4_RE.sub(lambda m: _dec(m, "utf-32-be"), s)
    return s


def blank_x_strings(rec: str):
    """\\X2\\/\\X4\\ エスケープを含む文字列だけを '' にする。(新レコード, 消した数)"""
    o, c = find_parens(rec)
    if o < 0:
        return rec, 0
    inner = rec[o + 1:c]
    cnt = 0

    def repl(m):
        nonlocal cnt
        if X_ESC_RE.search(m.group(0)):
            cnt += 1
            return "''"
        return m.group(0)

    new_inner = STRING_RE.sub(repl, inner)
    if cnt == 0:
        return rec, 0
    return rec[:o + 1] + new_inner + rec[c:], cnt


def iter_records(text: str):
    """トップレベルの ';' でレコード区間 (start, end) を列挙する。
    文字列リテラル内・コメント内の ';' は区切りとして扱わない。
    戻り値: (records, comments)  いずれも (start, end) のリスト
    """
    records, comments = [], []
    i, n = 0, len(text)
    start = 0
    in_str = False
    com_start = -1
    while i < n:
        c = text[i]
        if in_str:
            if c == "'":
                if i + 1 < n and text[i + 1] == "'":  # エスケープされた '
                    i += 2
                    continue
                in_str = False
            i += 1
            continue
        if com_start >= 0:
            if c == "*" and i + 1 < n and text[i + 1] == "/":
                comments.append((com_start, i + 2))
                com_start = -1
                i += 2
                continue
            i += 1
            continue
        if c == "'":
            in_str = True
        elif c == "/" and i + 1 < n and text[i + 1] == "*":
            com_start = i
            i += 1
        elif c == ";":
            records.append((start, i))
            start = i + 1
        i += 1
    return records, comments


def rec_without_comments(text: str, s: int, e: int, comments) -> str:
    """レコード区間からコメントを除いたテキストを返す(解析用)"""
    if not comments:
        return text[s:e]
    out, pos = [], s
    for a, b in comments:
        if b <= s or a >= e:
            continue
        out.append(text[pos:max(a, s)])
        pos = min(b, e)
    out.append(text[pos:e])
    return "".join(out)


def find_parens(rec: str):
    """レコード内の最初の '(' と対応する ')' の位置。文字列内は無視。"""
    in_str = False
    depth = 0
    open_i = -1
    i, n = 0, len(rec)
    while i < n:
        c = rec[i]
        if in_str:
            if c == "'":
                if i + 1 < n and rec[i + 1] == "'":
                    i += 2
                    continue
                in_str = False
            i += 1
            continue
        if c == "'":
            in_str = True
        elif c == "(":
            if depth == 0:
                open_i = i
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return open_i, i
        i += 1
    return -1, -1


def split_params(s: str):
    """括弧の中身をトップレベルのカンマで分割(ネスト括弧・文字列対応)"""
    parts, buf = [], []
    depth = 0
    in_str = False
    i, n = 0, len(s)
    while i < n:
        c = s[i]
        if in_str:
            buf.append(c)
            if c == "'":
                if i + 1 < n and s[i + 1] == "'":
                    buf.append(s[i + 1])
                    i += 2
                    continue
                in_str = False
            i += 1
            continue
        if c == "'":
            in_str = True
            buf.append(c)
        elif c == "(":
            depth += 1
            buf.append(c)
        elif c == ")":
            depth -= 1
            buf.append(c)
        elif c == "," and depth == 0:
            parts.append("".join(buf).strip())
            buf = []
        else:
            buf.append(c)
        i += 1
    tail = "".join(buf).strip()
    if tail or parts:
        parts.append(tail)
    return parts


def step_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def unstep_str(tok: str) -> str:
    tok = tok.strip()
    if len(tok) >= 2 and tok[0] == "'" and tok[-1] == "'":
        return tok[1:-1].replace("''", "'")
    return tok


def blank_strings(rec: str):
    """レコードのパラメータ部の文字列を全部 '' にする。(新レコード, 消した数)"""
    o, c = find_parens(rec)
    if o < 0:
        return rec, 0
    inner = rec[o + 1:c]
    n = sum(1 for m in STRING_RE.finditer(inner) if len(m.group(0)) > 2)
    if n == 0:
        return rec, 0
    return rec[:o + 1] + STRING_RE.sub("''", inner) + rec[c:], n


def neutralize_dates(rec: str, ename: str):
    """CALENDAR_DATE / LOCAL_TIME の数値を 1970-01-01 00:00:00 相当に"""
    o, c = find_parens(rec)
    if o < 0:
        return rec, False
    params = split_params(rec[o + 1:c])
    changed = False
    if ename == "CALENDAR_DATE":
        # (year_component, day_component, month_component)
        defaults = ["1970", "1", "1"]
        for i, p in enumerate(params):
            if INT_RE.match(p):
                params[i] = defaults[i] if i < 3 else "0"
                changed = True
    else:  # LOCAL_TIME (hour, [minute], [second], zone)
        for i, p in enumerate(params):
            if INT_RE.match(p):
                params[i] = "0"
                changed = True
            elif REAL_RE.match(p):
                params[i] = "0.0"
                changed = True
    if not changed:
        return rec, False
    return rec[:o + 1] + ",".join(params) + rec[c:], True


def strip_comments_text(text: str) -> str:
    """テキスト全体から /* */ コメントを除去(文字列内は保護)"""
    res = []
    i, n = 0, len(text)
    in_str = False
    while i < n:
        c = text[i]
        if in_str:
            res.append(c)
            if c == "'":
                if i + 1 < n and text[i + 1] == "'":
                    res.append(text[i + 1])
                    i += 2
                    continue
                in_str = False
            i += 1
            continue
        if c == "'":
            in_str = True
            res.append(c)
            i += 1
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "*":
            j = text.find("*/", i + 2)
            if j < 0:  # 閉じてない壊れコメントはそのまま残す
                res.append(text[i:])
                break
            i = j + 2
            continue
        res.append(c)
        i += 1
    return "".join(res)


# ---------------------------------------------------------------- メイン処理

def process(text: str, records, comments, opts):
    """レコードを走査してレポートを作り、scanでなければ置換後テキストを返す"""
    repls = [None] * len(records)
    rep = {
        "header": None,
        "file_desc": None,
        "scrubbed": Counter(),
        "samples": [],
        "strings_blanked": 0,
        "dates": 0,
        "dates_changed": 0,
        "products": [],
        "product_renamed": 0,
        "x2_blanked": 0,
        "x2_found": 0,
        "data_strings": Counter(),
        "comments": [text[a:b] for a, b in comments],
    }
    section = None

    for idx, (s, e) in enumerate(records):
        rec = rec_without_comments(text, s, e, comments)
        key = rec.strip().upper()
        if key == "HEADER":
            section = "H"
            continue
        if key == "DATA" or key.startswith("DATA("):  # ed3は DATA('name',...) 形式もある
            section = "D"
            continue
        if key == "ENDSEC":
            section = None
            continue

        if section == "H":
            m = HEADER_ENT_RE.match(rec)
            if not m:
                continue
            hname = m.group(1).upper()
            o, c = find_parens(rec)
            if o < 0:
                continue
            params = split_params(rec[o + 1:c])
            lead = rec[:len(rec) - len(rec.lstrip())]

            if hname == "FILE_NAME":
                while len(params) < 7:
                    params.append("''")
                rep["header"] = {
                    "name": unstep_str(params[0]),
                    "timestamp": unstep_str(params[1]),
                    "author": params[2],
                    "organization": params[3],
                    "preprocessor": unstep_str(params[4]),
                    "originating_system": unstep_str(params[5]),
                    "authorisation": unstep_str(params[6]),
                }
                if opts.scan:
                    continue
                if opts.name is not None:
                    new_name = to_raw(opts.name)
                elif opts.keep_name:
                    new_name = rep["header"]["name"]
                else:
                    # フルパス → ファイル名のみ(Windows/Unix両対応)
                    new_name = re.split(r"[\\/]", rep["header"]["name"])[-1]
                ts = rep["header"]["timestamp"] if opts.keep_dates else EPOCH_TS
                repls[idx] = (lead + "FILE_NAME(" + step_str(new_name) + ","
                              + step_str(ts) + ",(''),(''),'','','')")

            elif hname == "FILE_DESCRIPTION":
                rep["file_desc"] = params[0] if params else "()"
                if opts.scan:
                    continue
                impl = params[1] if len(params) > 1 else "'2;1'"
                repls[idx] = lead + "FILE_DESCRIPTION((''),%s)" % impl

        elif section == "D":
            m = ENTITY_RE.match(rec)
            if not m:
                continue
            ename = m.group(1).upper()

            if ename in SCRUB_STRING_ENTITIES:
                rep["scrubbed"][ename] += 1
                if len(rep["samples"]) < 8:
                    rep["samples"].append(rec.strip())
                if not opts.scan:
                    new_rec, n = blank_strings(rec)
                    if n:
                        repls[idx] = new_rec
                        rep["strings_blanked"] += n

            elif ename in DATE_ENTITIES:
                rep["dates"] += 1
                if not opts.scan and not opts.keep_dates:
                    new_rec, ch = neutralize_dates(rec, ename)
                    if ch:
                        repls[idx] = new_rec
                        rep["dates_changed"] += 1

            elif ename == "PRODUCT":
                o, c = find_parens(rec)
                params = split_params(rec[o + 1:c]) if o >= 0 else []
                if len(params) >= 2:
                    rep["products"].append(unstep_str(params[1]))
                if opts.product and not opts.scan and len(params) >= 2:
                    nv = step_str(to_raw(opts.product))
                    params[0] = nv
                    params[1] = nv
                    if len(params) >= 3 and params[2].startswith("'"):
                        params[2] = "''"  # description も空に
                    repls[idx] = rec[:o + 1] + ",".join(params) + rec[c:]
                    rep["product_renamed"] += 1

            elif opts.scan:
                # scan時: その他エンティティの非空文字列を収集(PII監査用)
                for mm in STRING_RE.finditer(rec):
                    v = mm.group(0)
                    if len(v) > 2:
                        rep["data_strings"][unstep_str(v)] += 1

            # 非ASCIIエスケープ(\X2\等)入り文字列 = フィーチャー名などのユーザー由来
            if X_ESC_RE.search(rec):
                if opts.scan:
                    rep["x2_found"] += sum(
                        1 for mm in STRING_RE.finditer(rec)
                        if X_ESC_RE.search(mm.group(0)))
                elif not opts.keep_x2 and repls[idx] is None:
                    new_rec, n = blank_x_strings(rec)
                    if n:
                        repls[idx] = new_rec
                        rep["x2_blanked"] += n

    if opts.scan:
        return None, rep

    # 出力テキストを組み立て(未変更レコードは元のバイト列をそのまま使う)
    out = []
    for (s, e), r in zip(records, repls):
        out.append((r if r is not None else text[s:e]) + ";")
    tail_start = records[-1][1] + 1 if records else 0
    out.append(text[tail_start:])
    new_text = "".join(out)

    if comments and not opts.keep_comments:
        new_text = strip_comments_text(new_text)

    return new_text, rep


# ---------------------------------------------------------------- レポート表示

def trunc(s: str, w: int = 96) -> str:
    s = " ".join(s.split())
    return s if len(s) <= w else s[:w - 1] + "…"


def print_scan(rep, src: Path, nrec: int, size: int):
    print(f"📄 {src.name}  ({size:,} bytes / {nrec:,} records)\n")
    print("[HEADER]")
    if rep["file_desc"] is not None:
        print(f"  FILE_DESCRIPTION  : {display(trunc(rep['file_desc']))}")
    h = rep["header"]
    if h:
        for k in ("name", "timestamp", "author", "organization",
                  "preprocessor", "originating_system", "authorisation"):
            print(f"  {k:<18}: {display(trunc(h[k]))}")
    else:
        print("  FILE_NAME が見つからない(非標準ファイル?)")

    print("\n[DATA]")
    if rep["scrubbed"]:
        counts = "  ".join(f"{k}×{v}" for k, v in rep["scrubbed"].items())
        print(f"  個人・組織系エンティティ: {counts}")
        for smp in rep["samples"]:
            print(f"    {display(trunc(smp))}")
    else:
        print("  個人・組織系エンティティ: なし")
    print(f"  日付エンティティ (CALENDAR_DATE/LOCAL_TIME): {rep['dates']}")
    if rep["x2_found"]:
        print(f"  非ASCII文字列 (\\X2\\ フィーチャー名など): {rep['x2_found']} ← 作成環境の言語がバレる")
    if rep["products"]:
        names = ", ".join(repr(display(p)) for p in rep["products"][:10])
        print(f"  PRODUCT 名: {names}")
    if rep["data_strings"]:
        print("  その他の非空文字列(上位・要目視チェック):")
        for v, n in rep["data_strings"].most_common(20):
            print(f"    {n:>4}× {display(trunc(v, 80))!r}")

    print(f"\n[コメント] {len(rep['comments'])} 件")
    for cm in rep["comments"][:5]:
        print(f"    {display(trunc(cm))}")


def print_result(rep, opts, dst: Path, size: int):
    if rep["header"]:
        h = rep["header"]
        leaks = [x for x in (h["author"], h["organization"], h["preprocessor"],
                             h["originating_system"], h["authorisation"])
                 if x not in ("('')", "()", "", "''")]
        print(f"✔ HEADER: author/組織/ソフト名/承認者 を消去 ({len(leaks)} 項目に情報あり)")
        if not opts.keep_dates:
            print(f"✔ HEADER: timestamp → {EPOCH_TS}")
        if not opts.keep_name:
            nn = opts.name if opts.name else re.split(r"[\\/]", h["name"])[-1]
            print(f"✔ HEADER: name → {display(nn)!r}")
    if rep["file_desc"] is not None:
        print("✔ FILE_DESCRIPTION を空に")
    if rep["strings_blanked"]:
        counts = " ".join(f"{k}×{v}" for k, v in rep["scrubbed"].items())
        print(f"✔ DATA: {counts} の文字列 {rep['strings_blanked']} 個を消去")
    if rep["dates_changed"]:
        print(f"✔ DATA: 日付エンティティ {rep['dates_changed']} 件を 1970-01-01 に")
    if rep["x2_blanked"]:
        print(f"✔ DATA: 非ASCII文字列(フィーチャー名など) {rep['x2_blanked']} 個を消去")
    if rep["product_renamed"]:
        print(f"✔ DATA: PRODUCT 名 → {opts.product!r} ({rep['product_renamed']} 件)")
    if rep["comments"] and not opts.keep_comments:
        print(f"✔ コメント {len(rep['comments'])} 件を除去")
    print(f"→ {dst}  ({size:,} bytes)")


# ---------------------------------------------------------------- エントリ

def sniff_and_prepare(text: str) -> str:
    """圧縮・非対応形式を検出。ZIP/gzipは自動解凍してテキストを返す。"""
    if text.startswith("PK\x03\x04"):  # ZIP (.stpZ など)
        import io
        import zipfile
        try:
            zf = zipfile.ZipFile(io.BytesIO(text.encode("latin-1")))
            cands = [n for n in zf.namelist()
                     if n.lower().endswith((".step", ".stp", ".p21", ".ste"))]
            if len(cands) != 1:
                sys.exit("エラー: ZIP内のSTEPを特定できない。内容: "
                         + ", ".join(zf.namelist()[:8]))
            print(f"ℹ ZIP圧縮STEPを検出 → 内包の {cands[0]} を処理(出力は非圧縮)")
            return zf.read(cands[0]).decode("latin-1")
        except zipfile.BadZipFile:
            sys.exit("エラー: ZIPとして開けなかった。")
    if text.startswith("\x1f\x8b"):  # gzip
        import gzip
        print("ℹ gzip圧縮を検出 → 解凍して処理(出力は非圧縮)")
        return gzip.decompress(text.encode("latin-1")).decode("latin-1")
    if text.startswith("\x89HDF"):
        sys.exit("エラー: バイナリ形式(HDF5 / STEP Part 26)には対応していない。")
    if text.lstrip("\xef\xbb\xbf \t\r\n").startswith("<?xml"):
        sys.exit("エラー: XML形式(STEP Part 28)には対応していない。")
    return text


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", help="入力 STEP ファイル (.step / .stp)")
    ap.add_argument("-o", "--output", help="出力先 (既定: <入力名>_clean.step)")
    ap.add_argument("--scan", action="store_true",
                    help="変更せず、識別情報のレポートだけ表示")
    ap.add_argument("--name", metavar="STR",
                    help="FILE_NAME の name をこの値に (既定: パスを除いたファイル名)")
    ap.add_argument("--keep-name", action="store_true",
                    help="FILE_NAME の name を変更しない")
    ap.add_argument("--keep-dates", action="store_true",
                    help="タイムスタンプ・日付エンティティを保持")
    ap.add_argument("--keep-comments", action="store_true",
                    help="/* コメント */ を残す")
    ap.add_argument("--keep-x2", action="store_true",
                    help="\\X2\\ 等の非ASCII文字列(フィーチャー名など)を残す")
    ap.add_argument("--product", metavar="STR",
                    help="PRODUCT の id/name をこの値に付け替え")
    args = ap.parse_args(argv)

    src = Path(args.input)
    if not src.is_file():
        sys.exit(f"エラー: {src} が見つからない")
    text = sniff_and_prepare(load(src))
    records, comments = iter_records(text)

    first = text[records[0][0]:records[0][1]] if records else ""
    if first.lstrip("\xef\xbb\xbf").strip().upper() != "ISO-10303-21":
        print("⚠ 先頭が ISO-10303-21 じゃない。STEPファイルか確認して。", file=sys.stderr)

    new_text, rep = process(text, records, comments, args)

    if args.scan:
        print_scan(rep, src, len(records), len(text))
        return

    dst = Path(args.output) if args.output else src.with_name(
        src.stem + "_clean" + (src.suffix or ".step"))
    save(dst, new_text)
    print_result(rep, args, dst, len(new_text))


if __name__ == "__main__":
    try:
        main()
    except BrokenPipeError:  # `| head` などにパイプした時用
        sys.exit(0)
